apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployments.deploy.digital.ai
spec:
  group: deploy.digital.ai
  version: v1
  scope: Namespaced
  names:
    plural: deployments
    singular: deployment
    kind: Deployment
    shortNames:
      - xld
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            package:
              type: string
            environment:
              type: string