apiVersion: xl-deploy/v1
kind: Deployment
spec:
  package: Applications/PetClinic-Ear/1.0.0
  environment: Environments/Tomcat-Dev
  onSuccessPolicy: ARCHIVE
  orchestrators:
    - sequential-by-deployed

